
use valk:http

fn handler(req: http:Request, res: http:Response) {
    // Set output to html 200 "Hello world"
    res.html("Hello world!")
}

fn main() {
    let ip = "127.0.0.1"
    let port : u16 = 9000
    let s = http:Server.new(ip, port, handler) ! {
        println("Failed to initialize http server")
        return
    }
    println("HTTP server - http://" + ip + ":" + port)
    s.start()
}
