
use mem

struct InMemoryFile {
    ~ data: ptr
    ~ size: uint
    filename: String ("")
    mime_type: String ("application/octet-stream")

    static fn create_from_ptr(data: ptr, size: uint) SELF {
        let d : ptr = null @as ptr
        if size > 0 {
            d = mem:alloc(size)
            mem:copy(data, d, size)
        }
        return SELF {
            data: d
            size: size
        }
    }
}
